Parameters:
  BinFinderKeyName:
    Description: key pair name
    Type: String
  DefaultVPCId:
    Description: Default VPC Id
    Type: String
  
Resources:
  # BinFinderKeyPair:
  #   Type: AWS::EC2::KeyPair
  #   DeletionPolicy: "Retain"
  #   Properties:
  #     KeyName: BinFinderKey
  #     PublicKeyMaterial: !Ref BinFinderPubKey

  BinFinderInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-07caf09b362be10b8
      InstanceType: t2.micro
      KeyName: !Ref BinFinderKeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          GroupSet:
            - !Ref BinFinderSSHSecurityGroup
            - !Ref BinFinderHttpSecurityGroup
      Tags:
        - Key: Name
          Value: binfinder
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 30
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Pre-Bootstrap Configuration
          yum update -y
          yum install awscli -y
          # install docker
          yum install docker -y
          usermod -a -G docker ec2-user
          id ec2-user
          newgrp docker
          systemctl enable docker.service
          systemctl start docker.service
          systemctl status docker.service --no-pager
          docker version
          # install dvc
          wget https://dvc.org/download/linux-rpm/dvc-3.50.1
          mv dvc-3.50.1 ~/dvc-3.50.1-1.x86_64.rpm
          yum localinstall ~/dvc-3.50.1-1.x86_64.rpm -y

  # our EC2 security group
  BinFinderSSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      VpcId: !Ref DefaultVPCId

  # our second EC2 security group
  BinFinderHttpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !Ref DefaultVPCId

Outputs:
  BinFinderPublicIp:
    Description: Binfinder app host
    Value: !GetAtt BinFinderInstance.PublicDnsName